### ISSUE TITLE
SEO dasar

### ISSUE THREAD

**Issue by aadiityaak** [VelocityDeveloper/velocity-addons#1]
- og:image
- Home: title, description, keyword. Single - Auto generate
- /sitemap.xml

**Comment by adityathok** [comment]
- [fix seo selain home](https://github.com/VelocityDeveloper/velocity-addons/commit/f781c64e039e6ec532db09b9cd4becc8c790693e)
- [fix og image logic](https://github.com/VelocityDeveloper/velocity-addons/commit/95545309a6ae603cd2e4553c0708e7f3f4a9c9ed)
- [add seo basic in plugin](https://github.com/VelocityDeveloper/velocity-addons/commit/28ea297b8e09b235d6416038ccfe2fd479670533)
