### ISSUE TITLE
Shortcode jumlah pengunjung per post

### ISSUE THREAD

**Issue by VelocityDeveloper** [VelocityDeveloper/velocity-addons#3]

**Comment by adityathok** [comment]
[shortcode untuk HIT post/page](https://github.com/VelocityDeveloper/velocity-addons/commit/be3fd44b48e17b58342973f4d82b14cbfc9a43e8)

gunakan `[statistik_kunjungan stat:post]` atau` [statistik_kunjungan stat:post id:50] ` isi id dengan id post
