### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by VelocityDeveloper** [VelocityDeveloper/velocity-addons#5]
- keterangan tanda ":" diganti tanda "=" https://prnt.sc/wyTeYWosQ9xR

**Comment by dhytalu** [comment]
[https://github.com/VelocityDeveloper/velocity-addons/commit/f02ff2eaf6e6ab0904bd971ffcfe19c05b2ef86f](url)
![statistik](https://github.com/user-attachments/assets/87299a79-16d7-4a47-9533-45e4ab65ea2f)
